api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from .views import TypeViewSet, SigViewSet


router = DefaultRouter()
router.register('v1/type', TypeViewSet, 'api_type_list')
router.register('v1/sig', SigViewSet, 'api_sig_list')
schema_view = get_schema_view(title='Sigma API',
                              description='An API to query types and signatures',
                              version=1
                              )


urlpatterns = [
    path('api/', include(router.urls)),
    path('api/schema/', schema_view),
    path('api/docs/', include_docs_urls(title='Sigma API')),
]

sigma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('web.urls')),
    path('', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/models.py
from django.db import models
import datetime
from django.utils import timezone


class Type(models.Model):

    name = models.CharField(max_length=255, null=False, unique=True)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Signature(models.Model):

    ENABLED = 'enabled'
    DISABLED = 'disabled'
    TESTING = 'testing'
    PENDING = 'pending'
    EXPIRED = 'expired'
    STATUS = [
        (ENABLED, 'enabled'),
        (DISABLED, 'disabled'),
        (TESTING, 'testing'),
        (PENDING, 'pending'),
        (EXPIRED, 'expired'),
    ]
    text = models.TextField(null=False)
    type = models.ForeignKey(Type, on_delete=models.PROTECT)
    reference = models.CharField(max_length=255, blank=True)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    expiry = models.DateField(null=False, default=datetime.date.today() + timezone.timedelta(91))
    status = models.CharField(max_length=255, choices=STATUS, default=ENABLED)


    def __str__(self):
        return self.text

sigma/templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>Sigma About Page</h1>

<h3>API Quick start guide</h3>
List all signatures<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/sig/<br>
<br>
List all types<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/type/<br>
<br>
List one signature by sig_id<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/sig/1/<br>
<br>
List one type by type id<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/type/1/<br>
<br>
Search types (exact match) by name, id, (partial match) by name_like, comment<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/type/?name=md5<br>
<br>
Search signature (exact match) by type, type_id, text, id, type, (partial match) by type_like, text_like, comment<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/sig/?type=snort<br>
<br>
Create new type<br>
curl -X POST -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/type/ -d '{"name":"ja3", "comment": "ssl fingerprint md5hash"}'<br>
<br>
Create new signature (must know the type_id)<br>
curl -X POST -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/sig/ -d '{"text":"baddomain.com", "type":"bad_domain"}'<br>
<br>
Delete type by type id (successful delete returns a 204 No Content)<br>
This will fail if the type has signatures related to it. Signatures related to a type must be deleted first before the type will delete successfully<br>
curl -X DELETE -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/type/5/<br>
<br>
Delete signature by sig id (successful delete returns a 204 No Content)<br>
curl -X DELETE -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/sig/7/<br>

{% endblock content %}

sigma/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title>Sigma</title>

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid">

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'sigma-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'sigma-about' %}">About</a>
              {% if user.is_superuser %}
              <a class="nav-item nav-link" href="/admin/">Admin</a>
              <a class="nav-item nav-link" href="/admin/"></a>
              {% endif %}
           </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">{{ user.username }}'s Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-2">
          <div class="content-section">
            <h3>Sigma</h3>
            <p class='text-muted'>Quick links
              <ul class="list-group">
                {% if user.is_authenticated %}
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'type-list' %}">List Types</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'type-search' %}">Search Types</a>
                {% if perms.web.add_type %}
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'type-create' %}">New Type</a>
                {% endif %}
                <br>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'sig-list' %}"">List Sigs</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'sig-search' %}">Search Sigs</a>
                {% if perms.web.add_signature %}
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'sig-create' %}">New Sig</a>
                {% endif %}
                <br>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'api-root' %}">API Explore</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="/api/docs/">API Docs</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="/api/schema">API Schema</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="/api/docs/#users-api-token-auth-create">API Token</a>
                  {% endif %}
              </ul>
            </p>
          </div>
        </div>

        <div class="col-md-10">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>


      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

sigma/templates/home.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
    <h2>Recent Type updates</h2>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            {% if perms.web.change_type %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for type in types %}
        <tr>
            <td>{{type.name}}</td>
            <td>{{type.comment|linebreaks}}</td>
            <td>{{type.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{type.modified|date:"Y-m-d H:i:s"}}</td>
            {% if perms.web.change_type %}
            <td><a href="{% url 'type-update' type.id %}">update</a>
                <a href="{% url 'type-delete' type.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
<br>
    <h2>Recent Signature updates</h2>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Status</th>
            <th>Reference</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Expires</th>
            {% if perms.web.change_signature %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for sig in sigs %}
        <tr>
            <td>{{sig.text|linebreaks}}</td>
            <td>{{sig.type}}</td>
            <td>{{sig.status}}</td>
            <td>{{sig.reference}}</td>
            <td>{{sig.comment|linebreaks}}</td>
            <td>{{sig.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{sig.modified|date:"Y-m-d H:i:s"}}</td>
            <td>{{sig.expiry|date:"Y-m-d"}}</td>
            {% if perms.web.change_signature %}
            <td><a href="{% url 'sig-update' sig.id %}">update</a>
                <a href="{% url 'sig-delete' sig.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
<br>
    <h2>Recent Expired Signatures</h2>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Status</th>
            <th>Reference</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Expires</th>
            {% if perms.web.change_signature %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for exp in expired %}
        <tr>
            <td>{{exp.text|linebreaks}}</td>
            <td>{{exp.type}}</td>
            <td>{{exp.status}}</td>
            <td>{{exp.reference}}</td>
            <td>{{exp.comment|linebreaks}}</td>
            <td>{{exp.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{exp.modified|date:"Y-m-d H:i:s"}}</td>
            <td>{{exp.expiry|date:"Y-m-d"}}</td>
            {% if perms.web.change_signature %}
            <td><a href="{% url 'sig-update' exp.id %}">update</a>
                <a href="{% url 'sig-delete' exp.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
<br>
    <h2>Next to Expire Signatures</h2>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Status</th>
            <th>Reference</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Expires</th>
            {% if perms.web.change_signature %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for exp in expiring %}
        <tr>
            <td>{{exp.text|linebreaks}}</td>
            <td>{{exp.type}}</td>
            <td>{{exp.status}}</td>
            <td>{{exp.reference}}</td>
            <td>{{exp.comment|linebreaks}}</td>
            <td>{{exp.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{exp.modified|date:"Y-m-d H:i:s"}}</td>
            <td>{{exp.expiry|date:"Y-m-d"}}</td>
            {% if perms.web.change_signature %}
            <td><a href="{% url 'sig-update' exp.id %}">update</a>
                <a href="{% url 'sig-delete' exp.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
{% else %}
Please login to use sigma
{% endif %}
{% endblock content %}