api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from .views import TypeViewSet, SigViewSet


router = DefaultRouter()
router.register('v1/type', TypeViewSet, 'api_type_list')
router.register('v1/sig', SigViewSet, 'api_sig_list')
schema_view = get_schema_view(title='Sigma API',
                              description='An API to query types and signatures',
                              version=1
                              )


urlpatterns = [
    path('api/', include(router.urls)),
    path('api/schema/', schema_view),
    path('api/docs/', include_docs_urls(title='Sigma API')),
]

sigma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('web.urls')),
    path('', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/models.py
from django.db import models
import datetime
from django.utils import timezone


class Type(models.Model):

    name = models.CharField(max_length=255, null=False, unique=True)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Signature(models.Model):

    ENABLED = 'enabled'
    DISABLED = 'disabled'
    TESTING = 'testing'
    PENDING = 'pending'
    EXPIRED = 'expired'
    STATUS = [
        (ENABLED, 'enabled'),
        (DISABLED, 'disabled'),
        (TESTING, 'testing'),
        (PENDING, 'pending'),
        (EXPIRED, 'expired'),
    ]
    text = models.TextField(null=False)
    type = models.ForeignKey(Type, on_delete=models.PROTECT)
    reference = models.CharField(max_length=255, blank=True)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    expiry = models.DateField(null=False, default=datetime.date.today() + timezone.timedelta(91))
    status = models.CharField(max_length=255, choices=STATUS, default=ENABLED)


    def __str__(self):
        return self.text

web/templates/web/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content%}
<div class="container">
    <h2>Search</h2>
    <form class="form-group col-sm-2 col-md-10" action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-outline-info" type="submit">Search</button>
    </form>
</div>
{% endblock %}

web/templates/web/signature_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Sig</legend>
                <h2>Are you sure you want to delete the Sig "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'sigma-home' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

web/templates/web/signature_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create or Update Sig</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

web/templates/web/signature_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <h1>Sigs</h1>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Text</th>
            <th>Type</th>
            <th>Status</th>
            <th>Reference</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Expires</th>
            {% if perms.web.delete_signature %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for object in object_list %}
        <tr>
            <td>{{object.text|linebreaks}}</td>
            <td>{{object.type}}</td>
            <td>{{object.status}}</td>
            <td>{{object.reference}}</td>
            <td>{{object.comment|linebreaks}}</td>
            <td>{{object.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{object.modified|date:"Y-m-d H:i:s"}}</td>
            <td>{{object.expiry|date:"Y-m-d"}}</td>
            {% if perms.web.delete_signature %}
            <td><a href="{% url 'sig-update' object.id %}">update</a>
                <a href="{% url 'sig-delete' object.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    {% endif %}
</div>
{% endblock content %}

web/templates/web/type_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Type</legend>
                <h2>Are you sure you want to delete the Type "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'sigma-home' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

web/templates/web/type_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create or Update Type</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

web/templates/web/type_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <h1>Type</h1>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            {% if perms.web.delete_type %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for object in object_list %}
        <tr>
            <td>{{object.name}}</td>
            <td>{{object.comment|linebreaks}}</td>
            <td>{{object.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{object.modified|date:"Y-m-d H:i:s"}}</td>
            {% if perms.web.delete_type %}
            <td><a href="{% url 'type-update' object.id %}">update</a>
                <br>
                <a href="{% url 'type-delete' object.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    {% endif %}
</div>
{% endblock content %}